### ISSUE TITLE
TutorialIntervalPredictorModelTest fails verification in R2019a

### ISSUE THREAD

**Issue by FriesischScott** [cossan-working-group/OpenCossan#12]
The tutorial fails verification using MATLAB 2019a. It works perfectly in 2018b.

```
Stacktrace
================================================================================
Verification failed in tutorials.TutorialIntervalPredictorModelTest/runTest.
---------------------
Framework Diagnostic:
---------------------
verifyEqual failed.
--> The numeric values are not equal using "isequaln".
--> The error was not within absolute tolerance.
--> Failure table:
Actual Expected Error RelativeError AbsoluteTolerance
____________________ ________ ____________________ __________________ _________________
5.06961311148513e-05 0.0014 -0.00134930386888515 -0.963788477775106 0.001
Actual Value:
5.069613111485126e-05
Expected Value:
0.001400000000000
------------------
Stack Information:
------------------
In /var/lib/jenkins/workspace/OpenCossan_development/test/integration/+tutorials/TutorialTest.m (TutorialTest.runTest) at 26
================================================================================
```

**Comment by JCSadeghi** [comment]
Thanks, will take a look

**Comment by JCSadeghi** [comment]
This is strange - I just ran the tutorials on my local machine (Windows) in R2019a and they all pass!!
Indeed, I obtain the correct expected value in the tutorial!
```
Totals:
   4 Passed, 0 Failed, 0 Incomplete.
   17.3707 seconds testing time.
```

**Comment by FriesischScott** [comment]
OK, now that is weird. On the server they constantly fail. I'll have another look next week,

**Comment by FriesischScott** [comment]
For some unknown reason, `fmincon` behaves differently on the server with `R2019a` than it does with `R2018b`. The optimization is stable, it produces the same results every time on both machines. Using `active-set` instead of `sqp` as the algorithm in `fmincon` works, but it might be dependent on the problem at hand. I think I will deactivate this test until `R019b` comes out and check if that helps.

**Comment by JCSadeghi** [comment]
Nice catch!
