### ISSUE TITLE
Errors in TutorialLineSamplingOutput.m

### ISSUE THREAD

**Issue by Adolphus8** [cossan-working-group/OpenCossan#2]
• The class Sensitivity has no Constant property or Static method named 'gradientFiniteDifferences'.
• Error in TutorialLineSampling (line 108)
• Error in run (line 91)
• Error in TutorialLineSamplingOutput (line 14)

**Comment by JCSadeghi** [comment]
Ok, this looks like the same problem as #3 , should be an easy fix

**Comment by JCSadeghi** [comment]
Actually it is already fixed by commit #7
