### ISSUE TITLE
git clone in readme requires permissions

### ISSUE THREAD

**Issue by JCSadeghi** [cossan-working-group/OpenCossan#5]
Following the readme, I tried to run
``` git clone git@github.com:cossan-working-group/OpenCossan.git
Cloning into 'OpenCossan'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

This worked instead:
`git clone https://github.com/cossan-working-group/OpenCossan.git`

**Comment by FriesischScott** [comment]
The instructions are what you need to clone using ssh key based authorization. We should change it to the regular https way as that is what most people use.
